version: '3.1'
services:
  portal:
    container_name: justice-backend
    image: justice-backend
    ports:
      - "10050:10050"
    volumes:
      - ./volumes/logs:/logs
      - ./volumes/config:/config
    restart: always
    network_mode: "host"